Extended classes by adding basic Vec2f, Vec3f, Vec4f, Color and Quaternion functions.
GothicKit/ZenKit4Py pull request #1
Opened 2024-08-10 09:17 UTC by Serbernus

2024-08-10 16:49 UTC, lmichaelis requested changes
Thanks, you have submitted very high quality code! I'd like to request only two general changes and 5 small adjustments:

* Please add [PEP-484](https://peps.python.org/pep-0484/) type hints where applicable (including in dunder-methods but excluding the `self` parameter)
* Conversely, please remove types in documentation comments, they should be determined from function signatures instead (so `Returns: Vec2f: A new Vec2f ...` becomes just `Returns: A new Vec2f ...` and the parenthesised types for attributes and arguments can be left out).

2024-08-10 16:49 UTC, lmichaelis commented on src/zenkit/core/vec2f.py
> +        raise TypeError("Comparison is only supported between two Vec2f objects")
`__eq__` should return `False` instead of throwing when comparing against an object of another type.

2024-08-10 16:49 UTC, lmichaelis commented on src/zenkit/core/vec3f.py
> +        raise TypeError("Comparison is only supported between two Vec3f objects")
`__eq__` should return `False` instead of throwing when comparing against an object of another type.

2024-08-10 16:49 UTC, lmichaelis commented on src/zenkit/core/vec4f.py
> +        raise TypeError("Comparison is only supported between two Vec4f objects")
`__eq__` should return `False` instead of throwing when comparing against an object of another type.

2024-08-10 16:49 UTC, lmichaelis commented on src/zenkit/core/quat.py
> +class Quat(Structure):
`Quat` is missing `__eq__`

2024-08-10 16:49 UTC, lmichaelis commented on src/zenkit/core/color.py
> +class Color(Structure):
`Color` is missing `__eq__`

2024-08-10 20:28 UTC, Serbernus commented
I hope my last edit is that what you meant in your request.

2024-08-11 09:44 UTC, lmichaelis commented
Okay looks good now :+1:, thanks!

2024-08-11 09:45 UTC, merged